### PR TITLE
Metta update April 2022

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Comment by berkus** [comment]
Not sure should I be in that authors list, if not suitable I can drop myself.

**Comment by phil-opp** [comment]
> Not sure should I be in that authors list, if not suitable I can drop myself.

I'm happy to list everyone who contributed, so that's fine with me. Thanks!

**Comment by phil-opp** [comment]
Looks like I need to merge this manually because of some conflicts. I'm not at my computer right now, but I will do it later.

**Comment by berkus** [comment]
@phil-opp no worries, let me rebase it quickly.

**Comment by phil-opp** [comment]
Thanks!

**Pull request merged**
