### PR TITLE
add initial draft of the RustyHermit showcase

### PR DESCRIPTION
**Pull request by stlankes**
@phil-opp Do I include the images correctly?

In general, feel free to comment the post.

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot! Looks good to me overall. I left a few suggestions in https://github.com/stlankes/homepage/pull/1 (mostly typo&grammar fixes and some sub-headings). Feel free to integrate any (or none) of these suggestions, however you like.

**Comment by stlankes** [comment]
Thanks for the improvements and corrections!

**Review by phil-opp — APPROVED** [review]
Thanks! This is ready to be published from my side, we just need to update decide on a publication date (e.g. tomorrow) and update the `date` field of the post accordingly.

One more question: Do you want to post this to the Rust subreddit yourself after it's published or should I do it?

**Comment by stlankes** [comment]
I agree and I would prefer, if you post it.

**Comment by phil-opp** [comment]
Ok, thanks again!

**Comment by phil-opp** [comment]
@stlankes There was a comment in the reddit thread: https://www.reddit.com/r/rust/comments/l2r5zl/the_rustyhermit_unikernel/gk98iwr/

If you don't have a reddit account, I can forward an answer if you like.

**Comment by stlankes** [comment]
Sorry, I oversaw it. I will check it.

**Pull request merged**
