### PR TITLE
This Month in Rust OSDev: November 2022

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcoming "This Month in Rust OSDev: November 2022" post. Please add your content to this draft by creating a pull request against the next branch. All projects related to OS development in Rust are valid here, they don't need to be associated with the rust-osdev organization.

The post will be published around December 6.

### CODE REVIEW

**Comment by phip1611** [comment]
I'll add something in the next hour. Hope I'm not too late :D

**Comment by phil-opp** [comment]
Great, thanks a lot! We plan to publish around Dec 6, so that's the deadline.

**Comment by phil-opp** [comment]
I added basic changelogs for all rust-osdev projects. I also added a new "Announcements, News, and Blog Posts" section and tried to collect all relevant links from the past month. Please submit PRs for things that I missed!

cc @rust-osdev/uefi You really did a lot of work on the `uefi` crate this month, very impressive! I tried to manually group your changelog into subsections to make it clearer, but I'm not following the project closely enough to have all the context. So feel free to improve or rewrite this section if you like.

cc @kevinaboos I would love to include the recent changes to Theseus OS in this issue. Perhaps you have time to write a short update? I can also try to create a basic changelog based on the [recently merged PRs](https://github.com/theseus-os/Theseus/pulls?page=2&q=is%3Apr+is%3Aclosed+merged%3A%3E2022-10-01) if you're busy.

**Comment by kevinaboos** [comment]
> cc @kevinaboos I would love to include the recent changes to Theseus OS in this issue. Perhaps you have time to write a short update? I can also try to create a basic changelog based on the [recently merged PRs](https://github.com/theseus-os/Theseus/pulls?page=2&q=is%3Apr+is%3Aclosed+merged%3A%3E2022-10-01) if you're busy.

Thanks for the shout-out and the reminder! I'll definitely submit an update, but I may not be able to get to it until Dec 5th or 6th.

**Comment by kevinaboos** [comment]
> @kevinaboos No problem, then let's include Theseus in the next issue.

Ah, sorry about that, I'll look forward to the next issue.

**Pull request merged**
