### PR TITLE
This Month in Rust OSDev (November 2021)

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcoming _"This Month in Rust OSDev (November 2021)"_ post. Please add your content to this draft by creating a pull request against the `next` branch.

### CODE REVIEW

**Comment by phil-opp** [comment]
Published at https://rust-osdev.com/this-month/2021-11/

**Comment by berkus** [comment]
There isn't anything for December?

**Comment by phil-opp** [comment]
Thanks for the reminder, I'll prepare a new draft PR in a moment.

**Comment by phil-opp** [comment]
@berkus Done at https://github.com/rust-osdev/homepage/pull/79

**Pull request merged**
