### PR TITLE
Add section on Hermit rebranding

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by mkroening** [comment]
Thanks, @phil-opp :)

**Comment by phil-opp** [comment]
Thanks for submitting, I like the new logo!

Maybe you could add a sentence or two to introduce the Hermit project, for those who don't know it yet? You could also link to https://rust-osdev.com/showcase/rusty-hermit/, if it's still up-to-date.

**Comment by mkroening** [comment]
Thanks for the feedback. I added a few sentences.

I'll also rework the showcase on Monday. :)

**Comment by phil-opp** [comment]
Thanks a lot!

**Review by phil-opp — APPROVED** [review]

**Pull request merged**
