### PR TITLE
This Month in Rust OSDev (April 2021)

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcoming _"This Month in Rust OSDev (April 2021)"_ post. Please add your content to this draft by creating a pull request against the `next` branch.

### CODE REVIEW

**Comment by andre-richter** [comment]
Title still says **March** 2021

**Comment by phil-opp** [comment]
Thanks, fixed!

**Comment by phil-opp** [comment]
I added the changelogs for most of the `rust-osdev` projects. I think only `acpi` is missing now. @IsaacWoods Do you have time for it or should I do it?

If anyone else wants to add something to this post please let me know so that we don't publish it too early.

**Comment by IsaacWoods** [comment]
@phil-opp apologies for the delay, I'll get it done in the next few hours.

**Comment by phil-opp** [comment]
@IsaacWoods No worries at all. I was just trying to plan things, I didn't mean to rush you, sorry!

**Comment by IsaacWoods** [comment]
@phil-opp ah no you haven't; it's good to have someone making sure the newsletter gets out on time! PR is up.

**Comment by phil-opp** [comment]
Good to hear that, thanks! :)

**Comment by phil-opp** [comment]
Published at https://rust-osdev.com/this-month/2021-04/. Thanks everyone!

**Pull request merged**
