### PR TITLE
 This Month in Rust OSDev: April 2022

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcoming _"This Month in Rust OSDev: April 2022"_ post. Please add your content to this draft by creating a pull request against the `next` branch.

TODO:
- [x] Updates for all `rust-osdev` projects
- [x] Other projects
  - [x] `phil-opp/blog_os`
  - [x] `vesper` from @berkus

### CODE REVIEW

**Comment by berkus** [comment]
Thanks! Will provide the write up by the end of this week.

**Comment by phil-opp** [comment]
@rust-osdev/all It's time for the April issue of our newsletter. Please submit your content in the next few days!

**Comment by berkus** [comment]
#99

**Comment by berkus** [comment]
Also #98 from Andre

**Comment by phil-opp** [comment]
Published at https://rust-osdev.com/this-month/2022-04/

**Pull request merged**
