### PR TITLE
This Month in Rust OSDev (February 2022)

### PR DESCRIPTION
**Pull request by phil-opp**
it's time for our monthly newsletter again! Please add all the content you want to include by opening a pull request against the `next` branch in the next few days.

There is one small change to the template this month. To make it clearer that this organization is a community effort, I would like to list the maintainers for all `rust-osdev` projects. I hope this is fine with everyone.

cc @rust-osdev/all

### CODE REVIEW

**Comment by berkus** [comment]
I have an update for February, pls hang on - i will try to submit it tonight.

**Comment by phil-opp** [comment]
> I have an update for February, pls hang on - i will try to submit it tonight.

@berkus I plan to publish the post in a few hours, so if you still want to submit something, please do that as soon as possible.

**Comment by phil-opp** [comment]
I'm going to merge and release this now. @berkus We can still add your February update after publishing if you like, just file your PR against `main` instead of `next`.

**Comment by phil-opp** [comment]
Published at <https://rust-osdev.com/this-month/2022-02/>.

**Comment by berkus** [comment]
Ok, sorry, I got dragged into all sorts of other stuff meanwhile :(

I guess I will just submit it to the March update instead.

**Comment by phil-opp** [comment]
Ok, no worries!

**Comment by phil-opp** [comment]
@phip1611 Yes, of course! Sounds like a great candidate for this newsletter!

**Comment by berkus** [comment]
@phip1611 I think, as an OSdev forum we **want** to highlight (aka propaganda) things that people did themselves, for themselves, in the OSdev area, and hope it will be useful for others or at least give them interesting ideas. So you're definitely welcome!

**Pull request merged**
