### PR TITLE
Add entry for lucis-fluxum/ps2

### PR DESCRIPTION
**Pull request by lucis-fluxum**

### CODE REVIEW

**Comment by phil-opp** [comment]
Looks great, thanks!

One small question regarding the API: How to read the keyboard scancodes? For the mouse there is a [`read_data_packet`](https://docs.rs/ps2/0.1.0/ps2/struct.Mouse.html#method.read_data_packet) function, but I can't find anything similar for the [`Keyboard`](https://docs.rs/ps2/0.1.0/ps2/struct.Keyboard.html) type.

**Comment by lucis-fluxum** [comment]
Data is usually read through `Controller::read_data`. I only added `Mouse::read_data_packet` as a convenience method over `Controller::read_data` to make it easier to get mouse packets. I'll push out an update soon to clear up any confusion.

**Comment by phil-opp** [comment]
Makes sense, thanks! I just read up a bit on PS/2 on the OSDev wiki and it seems like when using polling there is no way to find out whether a data byte comes from the keyboard or the mouse (if both are activated). Do you know if this is true?

(I'm considering to first introduce polling-based keyboard/mouse input before introducing interrupts in the next revision of my _Writing an OS in Rust_ blog, so it would be great if this were possible.)

**Comment by lucis-fluxum** [comment]
From what I understand, there's no 100% reliable way to differentiate which device is putting data in the data buffer using polling. If your PS/2 controller or emulated controller uses bit 5 of the status register as a "mouse output buffer full" flag, that might be something to look into, or you could disable one device while listening for input from the other, but I think you have to use interrupts if you want to easily process input from both devices.

**Comment by phil-opp** [comment]
Thanks! I think I'll stick to a keyboard-only implementation then until we introduce interrupts.

**Pull request merged**
