### PR TITLE
Tweak GHA config

### PR DESCRIPTION
**Pull request by JohnTitor**
- Update some actions to v2
- Update Zola to v0.11.0
- Only deploy if `github.repository == 'rust-osdev/homepage'`

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot!

**Comment by phil-opp** [comment]
@JohnTitor Seems like the download-artifact update broke the deploy job: https://github.com/rust-osdev/homepage/runs/938097915?check_suite_focus=true

Do you have time to look into this?

**Comment by JohnTitor** [comment]
Ooops, this fails to deploy: https://github.com/rust-osdev/homepage/runs/938097915
Let me take a look...

**Comment by phil-opp** [comment]
Thanks!

**Pull request merged**
