### PR TITLE
doc: November 2021 status update from @berkus

### PR DESCRIPTION
**Pull request by berkus**
Hi! First time poster, hope it fits the format.

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
It does, thanks!

Perhaps you could add a few introductory sentences at the beginning to tell people what the project is about. Something like "Vesper is a capability-based single-address-space exokernel. This means ...".

**Comment by berkus** [comment]
Alright, will do!

**Comment by berkus** [comment]
@phil-opp I've updated it, please take a look.

**Comment by phil-opp** [comment]
Looks great, thanks a lot!

**Pull request merged**
