### PR TITLE
This Month in Rust OSDev: July 2022

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcoming _"This Month in Rust OSDev: July 2022"_ post. Please add your content to this draft by creating a pull request against the `next` branch. All projects related to OS development in Rust are valid here, they don't need to be associated with the `rust-osdev` organization.

The July post will be published in the first week of August.

TODO:

- [x] rust-osdev crates
- [x] ~phil-opp/blog_os~
- [x] Theseus
- [x] Mention https://github.com/rust-lang/rust/pull/99760

### CODE REVIEW

**Comment by kevinaboos** [comment]
@phil-opp thanks for considering Theseus! I didn't have a chance to submit a PR for July, but will definitely submit a PR for this month. Planning to finish that up today or tomorrow.

**Comment by kevinaboos** [comment]
Just submitted the update for Theseus. Thanks again!

**Comment by phil-opp** [comment]
Thanks everyone for the great submissions!

I'm sorry about the delayed release. The good news is that I now created a small script to autogenerate the changelog for `rust-osdev` projects, which should make future releases much easier.

**Comment by phil-opp** [comment]
Published at <https://rust-osdev.com/this-month/2022-07/>

**Pull request merged**
