### PR TITLE
This Month in Rust OSDev: April 2024 

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcoming "This Month in Rust OSDev: April 2024" post. Please add your content to this draft by creating a pull request against the `next` branch. All projects related to OS development in Rust are valid here, they don't need to be associated with the rust-osdev organization.

The post will be published around May 5th.

### CODE REVIEW

**Comment by RatCornu** [comment]
Hello! I'm working on a `no_std` library that could be interesting for OSdev and I will soon push a new version. Here is the link: https://codeberg.org/RatCornu/efs. Would you think it can be added in "Others Projects" sections ?

**Comment by phil-opp** [comment]
Yes, this fits our "Other Projects" section quite well! Just submit a PR against the `next` branch to add it.

Cool project!

**Comment by RatCornu** [comment]
> @RatCornu Yes, this fits our "Other Projects" section quite well! Just submit a PR against the `next` branch to add it. Cool project!
> […](#)
> On Fri, 26 Apr 2024, at 00:53, Rat Cornu wrote: Hello! I'm working on a `no_std` library that could be interesting for OSdev and I will soon push a new version. Here is the link: https://codeberg.org/RatCornu/efs. Would you think it can be added in "Others Projects" sections ?Message ID: ***@***.***>

Thanks! I deleted my message when I saw that I should have create a PR. I'll make one as soon as my project is a usable state!

**Comment by phil-opp** [comment]
I plan to publish the post later today, so please submit any content you like to add as soon as possible.

**Comment by phil-opp** [comment]
Published at <https://rust-osdev.com/this-month/2024-04/>. Draft PR for next issue: https://github.com/rust-osdev/homepage/pull/216n

**Pull request merged**
