### PR TITLE
This Month in Rust OSDev (January 2021)

### PR DESCRIPTION
**Pull request by phil-opp**
This is a draft for the upcomping _"This Month in Rust OSDev (January 2021)"_ post. Please add your content to this draft by creating pull requests against the `next` branch.

Todo:

- [x] uart_16550
- [x] RustyHermit post
- [x] cargo-xbuild
- [x] ACPI crates ([commits](https://github.com/rust-osdev/acpi/compare/4b6534bfd8de2459579e5e8ff82a640e9d83d1d6...master))
- [x] phil-opp/blog_os
- [x] uefi bootloader progress

### CODE REVIEW

**Comment by phil-opp** [comment]
@rust-osdev/all It's time for our monthly newsletter again. Let me know If you want to add any content!

**Comment by IsaacWoods** [comment]
I don't have much to talk about this month, and am unfortunately running short of time with other commitments. I'm happy to roll the `acpi` commits into next month (when hopefully I'll have some slightly more exciting progress), or I'm happy for you to add a little bit about it if you're writing up the other projects - up to you :)

**Comment by phil-opp** [comment]
@IsaacWoods Thanks for letting me know! I added a basic commit list for ACPI, I hope it's ok this way.

**Comment by phil-opp** [comment]
From my side this is ready to be merged. I plan to publish the post tomorrow, so please submit any content you like to add until then.

**Comment by GabrielMajeri** [comment]
@phil-opp The situation with `uefi-rs` is similar, there were only two very small commits in January. But there's a bigger refactoring which might come to fruition in February, and I'd like to include it in that news post.

**Comment by phil-opp** [comment]
@GabrielMajeri Thanks for the info!

I guess we're ready for the release then.

**Comment by stlankes** [comment]
I would add also PR. Give me an hour.

**Comment by phil-opp** [comment]
@stlankes Oh sorry, I just merged this pull request a few minutes ago. But I can wait before posting it to reddit etc, then you can add your content before anybody sees it hopefully. Would that work for you?

**Comment by stlankes** [comment]
No problem... I want to add just a notice that RustyHermit is able to run on [K8S](https://github.com/hermitcore/rusty-hermit/wiki/RustyHermit-on-K8S). Next time is also finde for me.

**Comment by phil-opp** [comment]
Ah, that's great! I would be fine waiting an hour or so, or mention it next time, however you prefer.

**Comment by stlankes** [comment]
Ok, I will write a short text.

**Comment by phil-opp** [comment]
With #42 merged, I just submitted the post to the Rust subreddit at https://www.reddit.com/r/rust/comments/ldvd4b/this_month_in_rust_osdev_january_2021/. Feel free to post it elsewhere too, of course.

**Pull request merged**
