### PR TITLE
Add Motor OS announcement.

### PR DESCRIPTION
**Pull request by lasiotus**

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Cool project! I wonder how you expose a Rust-based ABI, given that there is no stable Rust ABI yet?

Also, thanks for the shout-out!

**Comment by lasiotus** [comment]
Thanks! 

The kernel ABI is exposed via [moto-sys](https://crates.io/crates/moto-sys) crate, while the I/O via [moto-runtime](https://crates.io/crates/moto-runtime), which is a [dependency of Rust's stdlib](https://github.com/moturus/rust/blob/11da3b03674c26ca8066e88fea2bc6be7f494729/library/std/Cargo.toml#L46).

Pretty much everything there is very unstable yet, but the end result of porting the stdlib is that Rust code that relies only on Rust's stdlib compiles and runs, and has the stable Rust stdlib API to rely on. In other words, the project mimics Rust's stable/unstable setup: the higher-level API (stdlib) is stable, the lower-level details are not.

**Comment by phil-opp** [comment]
Thanks for the explanation! Looks like you use `repr(C)` for the lower-level ABI (e.g. `ProcessData`), so creating a C-compatible system library would work too, right? You just focus on userspace programs written in Rust for now?

**Comment by lasiotus** [comment]
Yes, exactly!

**Pull request merged**
